#!/bin/bash

# Copyright (C) 2018 The Board of Trustees of the Leland Stanford Junior University.

# The contents of this file are licensed under the
# GNU General Public License, Version 3.
# In addition, documentation in this file is licensed under the
# Creative Commons Attribution-ShareAlike 3.0 Unported.
# See the files `LICENSE` and `LICENSE.cc-by-sa-3` for full license text.

. scripts/setup.sh

# This is unusual, in that we're not handing off to Python immediately!
echo 'Welcome!'
echo 'It is time to finish up installation.'

# We'll use shell to make sure the Python modules are installed.
echo ''
echo 'Making sure pip is up-to-date...'
$VENV_PATH/bin/pip install --upgrade pip

echo ''
echo 'Installing/upgrading required packages...'
$VENV_PATH/bin/pip install -r requirements.txt --no-warn-script-location

# Now hand off to Python.
echo ''
exec $VENV_PATH/bin/python scripts/finish_install.py $@
